sudo: required
dist: xenial
language: python

python: 3.6
install: true

git:
  depth: false
  quiet: true

services: docker

stages:
  - name: unittests
    if: type IN (push, pull_request)
  - name: image
    if: type IN (push, pull_request)


jobs:
  include:
    - stage: unittests
      python: 3.6
      before_script:
        - sudo apt-get update
        - sudo apt-get install build-essential fakeroot -y
        - sudo apt-get install python3-numpy libpython3-dev cython3 zlib1g-dev dh-python zlib1g-dev -y
        - pip install tox-travis
      script: tox
    - stage: image
      script:
        - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
             cd deploy ;
             docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
             docker build -t cscfi/beacon-python . ;
             docker push cscfi/beacon-python:latest;
          fi

notifications:
  email: false
