version: '3.2'

services:
  postgres:
    hostname: postgres
    image: postgres:11.2
    environment:
      POSTGRES_USER: beacon
      POSTGRES_DB: beacondb
      POSTGRES_PASSWORD: beacon
    ports:
      - 5432:5432
    volumes:
      - ../data/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  beacon:
    hostname: beacon
    image: cscfi/beacon-python
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres
    links:
    - postgres:postgres
    ports:
      - 5050:5050
    restart: on-failure
