name: Integration Tests

on:
  pull_request:

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    
    runs-on: ${{ matrix.os }}

    name: Integration Tests

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install requirements
      run: |
        pip install aiohttp
        pip install requests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: network=host
    
    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: localhost:5000/beacon-python:latest
        cache-from: localhost:5000/beacon-python:latest
        cache-to: type=local,dest=/tmp/.buildx-cache
        
    - name: Start Services
      run: |
        docker-compose -f deploy/test/docker-compose.yml up -d
        sleep 10
        docker exec test_beacon_1 beacon_init /exdata/ALL.chrMT.phase3_callmom-v0_4.20130502.genotypes.vcf.gz /exdata/example_metadata.json
        docker exec test_beacon_1 beacon_init /exdata/ALL.chrMT.phase3_callmom-v0_4.20130502.genotypes.vcf.gz /exdata/example_metadata_registered.json
        docker exec test_beacon_1 beacon_init /exdata/ALL.chrMT.phase3_callmom-v0_4.20130502.genotypes.vcf.gz /exdata/example_metadata_controlled.json
        docker exec test_beacon_1 beacon_init /exdata/ALL.chrMT.phase3_callmom-v0_4.20130502.genotypes.vcf.gz /exdata/example_metadata_controlled1.json

    - name: Run Integration test
      run: |
        python deploy/test/run_tests.py

    - name: Collect logs from docker
      if: ${{ failure() }}
      run: cd deploy && docker-compose logs --no-color -t > ../tests/dockerlogs || true

    - name: Persist log files
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: test_debugging_help
        path: tests
