name: Python style check

on: [push]

jobs:
  style_check:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
      
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test flake8 syntax with tox
      run: tox -e flake8
    - name: Do bandit static check with tox
      run: tox -e bandit
    - name: Black formatting check
      run: tox -e black
    - name: Install libcurl-devel
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
    - name: Type hints check
      run: tox -e mypy
