name: Python Unit Tests

on:
  push:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  unit_test:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install libcurl-devel
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions coveragepy-lcov
    - name: Run unit tests for python 3.8
      run: |
        tox -e unit_tests
        coveragepy-lcov --output_file_path lcov.info
    - name: Send coverage to coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: lcov.info
